Calouros guide
BRUTEUdesc/bruteudesc.github.io pull request #20
Opened 2020-01-29 20:14 UTC by IgorFroehner

Tava de bobeira nas férias e pensei em fazer esse post

2020-02-13 11:42 UTC, VGasparini commented on _posts/starterpack.md
> +Se você já sabe os comandos básicos(input, operações matematicas e output) de alguma linguagem de programação (menos visualg) pode clicar [aqui](#competitive-programming) para pular esta parte.
matemáticas

2020-02-13 11:43 UTC, VGasparini commented on _posts/starterpack.md
> +Printar váriaveis formatando a saída(o mais importante até aqui):<br>
variáveis

2020-02-13 11:51 UTC, VGasparini requested changes
@IgorFroehner achei muito boa tua iniciativa. Só adicionei algumas correções ortográficas e mudei algumas frases. Fique livre para reescrever se achar que não ficou bom.
Assim que terminar de corrigir, me marca no PR ( @VGasparini  ), senão não recebo notificação.

Vlwww

2020-02-13 11:51 UTC, VGasparini commented on _posts/starterpack.md
> +`a` será do tipo string, para fazer a converção quando você quer um número inteiro:<br>
conversão

2020-02-13 11:51 UTC, VGasparini commented on _posts/starterpack.md
> +Printar váriaveis formatando a saída(o mais importante até aqui):<br>
variáveis

2020-02-13 11:51 UTC, VGasparini commented on _posts/starterpack.md
> +Se você já sabe os comandos básicos(input, operações matematicas e output) de alguma linguagem de programação (menos visualg) pode clicar [aqui](#competitive-programming) para pular esta parte.
matemáticas

2020-02-13 11:51 UTC, VGasparini commented on _posts/starterpack.md
> +Neste o `+` pode ser substituido por qualquer uma das outras operações(- , *, /)
Neste caso, o `+` pode ser substituído por qualquer uma das outras operações (`-, *, /, %`)

2020-02-13 11:51 UTC, VGasparini commented on _posts/starterpack.md
> +URI é o online judge que a gente mais usa na UDESC, pelo menos no começo... E entrar na competição do ranking da udesc vai ser um bom insentivo.
incentivo

2020-02-13 11:51 UTC, VGasparini commented on _posts/starterpack.md
> +    São corretores de código sem coração, olhos ou ouvidos. O que quero dizer é que eles não vão olhar seu código diretamente, não vão ver suas variáveis ou seus comentários chingando o judge.
xingando

2020-02-13 11:51 UTC, VGasparini commented on _posts/starterpack.md
> +    Os problemas sempre são compostos por um enunsiado, uma explicação sobre a entrada que vai ser dada, sobre como a saida é esperada, e um input sample com a saida experada para ela, ajudando nos t
Os problemas sempre são compostos por um enunciado, uma explicação sobre a entrada que vai ser dada, sobre como a saída é esperada, e um input sample com a saída esperada para ela, ajudando nos testes antes de dar o submit.

2020-02-13 11:51 UTC, VGasparini commented on _posts/starterpack.md
> +    <font color=#0a0> **Acceped** </font>: Se você conseguiu essa resposta parabéns, você solucionou o problema - mas mesmo assim leia o que significam as outras respostas. Se não foi aceito faz part
Accepted

2020-02-13 11:51 UTC, VGasparini commented on _posts/starterpack.md
> +    <font color=#660> **Presentation error** </font>: Um dos erros mais comuns no problema 1001, é quando você acerta as entradas mas não do jeito que foi pedido no problema. Quando, em C por exemplo
Quando, por exemplo, esquecemos de quebrar linha (`\n`) no final de todos os prints.

2020-02-13 11:51 UTC, VGasparini commented on _posts/starterpack.md
> +    <font color=#004fc5> **Time limit exeeded** </font>: É uma das coisas que torna os problemas mais dificeis mais dificeis, o seu código tem um tempo limite para executar e dar a resposta, geralmen
<font color=#004fc5> **Time limit exceeded** </font>: É uma das coisas que torna os problemas difíceis mais difíceis, o seu código tem um tempo limite para executar e dar a resposta, geralmente 1s, e se passar disso terá o tempo limite excedido. É por causa desse erro que você vai ouvir muito falar em complexidade de algoritmo.

2020-02-13 12:12 UTC, elisa-frohlich reviewed
Alguns errinhos ortográficos que eu recomendo a correção, apesar de que o Gasparini mandou um pouco antes. No mais, achei muito da hora a ideia do post.

2020-02-13 12:12 UTC, joao-frohlich commented on _posts/2020-01-29-calouros-guide.markdown
> +URI é o online judge que a gente mais usa na UDESC, pelo menos no começo... E entrar na competição do ranking da udesc vai ser um bom insentivo.
```suggestion
URI é o online judge que a gente mais usa na UDESC, pelo menos no começo... E entrar na competição do ranking da udesc vai ser um bom incentivo.
```

2020-02-13 12:12 UTC, joao-frohlich commented on _posts/2020-01-29-calouros-guide.markdown
> +São corretores de código automáticos sem coração, olhos ou ouvidos. O que quero dizer é que eles não vão olhar seu código diretamente, não vão ver suas variáveis ou seus comentários chingando o judge
```suggestion
São corretores de código automáticos sem coração, olhos ou ouvidos. O que quero dizer é que eles não vão olhar seu código diretamente, não vão ver suas variáveis ou seus comentários xingando o judge.
```

2020-02-13 12:12 UTC, joao-frohlich commented on _posts/2020-01-29-calouros-guide.markdown
> +Os problemas sempre são compostos por um enunsiado, uma explicação sobre a entrada que vai ser dada, sobre como a saida é esperada, e um input sample com a saida experada para ela, ajudando nos teste
```suggestion
Os problemas sempre são compostos por um enunciado, uma explicação sobre a entrada que vai ser dada, sobre como a saida é esperada, e um input sample com a saida esperada para ela, ajudando nos testes antes de dar o 
```

2020-02-13 12:12 UTC, joao-frohlich commented on _posts/2020-01-29-calouros-guide.markdown
> +<font color=#0a0> **Acceped** </font>: Se você conseguiu essa resposta parabéns, você solucionou o problema - mas mesmo assim leia o que significam as outras respostas. Se não foi aceito faz parte, t
```suggestion
<font color=#0a0> **Acceped** </font>: Se você conseguiu essa resposta parabéns, você solucionou o problema - mas mesmo assim leia o que significam as outras respostas. Se não foi aceito faz parte, tanto que esse problema vale bastante pontos, leia o significado das outras respostas para saber o que errou.
```

2020-02-13 12:12 UTC, joao-frohlich commented on _posts/2020-01-29-calouros-guide.markdown
> +<font color=#660> **Presentation error** </font>: Um dos erros mais comuns no problema 1001, é quando você acerta as entradas mas não do jeito que foi pedido no problema. Quando, em C por exemplo esq
```suggestion
<font color=#660> **Presentation error** </font>: Um dos erros mais comuns no problema 1001, é quando você acerta as entradas mas não do jeito que foi pedido no problema. Quando em C, por exemplo, você esquece de pular linha (`\n`). Isso é sempre uma coisa pedida nos problemas.
```

2020-02-13 12:12 UTC, joao-frohlich commented on _posts/2020-01-29-calouros-guide.markdown
> +<font color=#004fc5> **Time limit exeeded** </font>: É uma das coisas que torna os problemas mais dificeis mais dificeis, o seu código tem um tempo limite para executar e dar a resposta, geralmente 1
```suggestion
<font color=#004fc5> **Time limit exceeded** </font>: É uma das coisas que torna os problemas mais difíceis mais difíceis. O seu código tem um tempo limite para executar e dar a resposta, geralmente 1s, e se passar disso terá o tempo limite excedido. É por causa desse erro que você vai ouvir muito falar em complexidade de código. 
```

2020-02-13 12:12 UTC, joao-frohlich commented on _posts/2020-01-29-calouros-guide.markdown
> +Hora de codar! Abra seu editor de texto, crie um arquivo `a.py`. Primeiro vamos aprender a dar um output, o famoso print. É complicado vá com calma:
```suggestion
Hora de codar! Abra seu editor de texto, crie um arquivo `a.py`. Primeiro vamos aprender a dar um output, o famoso print. É complicado, vá com calma:
```

2020-02-13 12:12 UTC, joao-frohlich commented on _posts/2020-01-29-calouros-guide.markdown
> +Para rodar seu código só ir até o terminal ou prompt de comando, ir até a [pasta](https://www.google.com/search?q=como+navegar+pelas+pastas+no+prompt+de+comando&oq) em que você criou o arquivo e dar
```suggestion
Para rodar seu código é só ir até o terminal ou prompt de comando, ir até a [pasta](https://www.google.com/search?q=como+navegar+pelas+pastas+no+prompt+de+comando&oq) em que você criou o arquivo e dar o comando para executar `python3 a.py`.
```

2020-02-15 12:45 UTC, IgorFroehner commented on _posts/2020-01-29-calouros-guide.markdown
> +<font color=#0a0> **Acceped** </font>: Se você conseguiu essa resposta parabéns, você solucionou o problema - mas mesmo assim leia o que significam as outras respostas. Se não foi aceito faz parte, t
esse ta certo

2020-02-15 14:24 UTC, merged